# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Jagdish Tripathy"
email: jagdish.tripathy@bankofengland.co.uk
description: >-
  Research Adviser at the Bank of England. Research on household finance, real-estate markets, banking, and macro-prudential policy. Expertise in macroeconomics and causal inference.

minimal_mistakes_skin: air # (Or "default" or another for your preferred color palette)

author:
  name   : "Jagdish Tripathy"
  avatar : "/assets/images/Jagdish-photo.jpg"
  bio    : "Research Adviser, Bank of England"

  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/jagdish-tripathy-3a107b5/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jagdish-tripathy"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/jagdishtrip"

# Only "Research" and "CV" in the main nav
# (No "About Me" nav; About is front page)
navigation:
  main:
    - title: "Research"
      url: /research/
    - title: "CV"
      url: /cv/

# Footer links
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/jagdish-tripathy-3a107b5/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jagdish-tripathy"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/jagdishtrip"

# Defaults for pages
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true  # Show right profile card on all pages

# Disable posts, categories, and tags
collections:
  posts:
    output: false

# Don’t show blog/index in nav
# Optionally add:
# include:
#   - _pages
